app = "livestock-prod"
primary_region = "jnb"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
[http_service.concurrency]
type = "connections"
soft_limit = 20
hard_limit = 25
[[http_service.checks]]
interval = "30s"
grace_period = "10s"
method = "GET"
path = "/actuator/health"
timeout = "5s"

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1

[deploy]
release_command = "java -jar app.jar --spring.profiles.active=prod --spring.flyway.enabled=true"