spring:
  datasource:
    url: jdbc:h2:mem:livestock
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        transaction:
          jta:
            platform: no
  flyway:
    enabled: true
    locations: classpath:db/migration