name: Teardown Fly.io Dev
on:
  workflow_dispatch:
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  teardown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Destroy Postgres
        run: flyctl apps destroy livestock-dev-psql --yes || true
      - name: Destroy App
        run: flyctl apps destroy livestock-dev --yes || true